### ISSUE TITLE
Tracking issue for macro compiler

### ISSUE THREAD

**Issue by sdleffler** [boltlabs-inc/dialectic#48]
This is a tracking issue for the macro-compiler-dev branch (PR #36).

- [x] Allow the user to omit commas for some statements of split/choose/offer constructs (#45)
- [ ] Enumerative testing of the full macro compiler (nice to have but not necessary) (#40)
- [x] Random testing of the parser (#40)
- [x] Analyze control flow to report unreachable code and unproductive loops which would produce odd type errors (#41)
- [x] Write missing internal documentation for large and complex functions, especially transformations of the CFG
- [x] Write README documenting the whole compiler, including CFG passes and what they do/how they work and what invariants are upheld
